Fix missing type includes

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -634,9 +634,6 @@ GCONF_SCHEMAS_INSTALL_FALSE
 GCONF_SCHEMAS_INSTALL_TRUE
 GCONF_LIBS
 GCONF_CFLAGS
-GLIB2_18_DEFINES
-GLIB2_18_LIBS
-GLIB2_18_CFLAGS
 GLIB2_14_DEFINES
 GLIB2_14_LIBS
 GLIB2_14_CFLAGS
@@ -660,6 +657,9 @@ GLIB2_26_CFLAGS
 GLIB2_24_DEFINES
 GLIB2_24_LIBS
 GLIB2_24_CFLAGS
+GLIB2_18_DEFINES
+GLIB2_18_LIBS
+GLIB2_18_CFLAGS
 GTK2_24_DEFINES
 GTK2_22_DEFINES
 GTK2_20_DEFINES
@@ -871,6 +871,8 @@ X11_CFLAGS
 X11_LIBS
 GTK_CFLAGS
 GTK_LIBS
+GLIB2_18_CFLAGS
+GLIB2_18_LIBS
 GLIB2_24_CFLAGS
 GLIB2_24_LIBS
 GLIB2_26_CFLAGS
@@ -891,8 +893,6 @@ GTK2_24_CFLAGS
 GTK2_24_LIBS
 GLIB2_14_CFLAGS
 GLIB2_14_LIBS
-GLIB2_18_CFLAGS
-GLIB2_18_LIBS
 GCONF_CFLAGS
 GCONF_LIBS
 GIO_CFLAGS
@@ -1576,6 +1576,10 @@ Some influential environment variables:
   X11_LIBS    linker flags for X11, overriding pkg-config
   GTK_CFLAGS  C compiler flags for GTK, overriding pkg-config
   GTK_LIBS    linker flags for GTK, overriding pkg-config
+  GLIB2_18_CFLAGS
+              C compiler flags for GLIB2_18, overriding pkg-config
+  GLIB2_18_LIBS
+              linker flags for GLIB2_18, overriding pkg-config
   GLIB2_24_CFLAGS
               C compiler flags for GLIB2_24, overriding pkg-config
   GLIB2_24_LIBS
@@ -1614,10 +1618,6 @@ Some influential environment variables:
               C compiler flags for GLIB2_14, overriding pkg-config
   GLIB2_14_LIBS
               linker flags for GLIB2_14, overriding pkg-config
-  GLIB2_18_CFLAGS
-              C compiler flags for GLIB2_18, overriding pkg-config
-  GLIB2_18_LIBS
-              linker flags for GLIB2_18, overriding pkg-config
   GCONF_CFLAGS
               C compiler flags for GCONF, overriding pkg-config
   GCONF_LIBS  linker flags for GCONF, overriding pkg-config
@@ -13101,6 +13101,81 @@ $as_echo "#define GTK2_22_ENABLED 1" >>confdefs.h
 
 $as_echo "#define GTK2_24_ENABLED 1" >>confdefs.h
 
+
+
+
+pkg_failed=no
+{ $as_echo "$as_me:${as_lineno-$LINENO}: checking for GLIB2_18" >&5
+$as_echo_n "checking for GLIB2_18... " >&6; }
+
+if test -n "$GLIB2_18_CFLAGS"; then
+    pkg_cv_GLIB2_18_CFLAGS="$GLIB2_18_CFLAGS"
+ elif test -n "$PKG_CONFIG"; then
+    if test -n "$PKG_CONFIG" && \
+    { { $as_echo "$as_me:${as_lineno-$LINENO}: \$PKG_CONFIG --exists --print-errors \"glib-2.0 >= 2.18.0\""; } >&5
+  ($PKG_CONFIG --exists --print-errors "glib-2.0 >= 2.18.0") 2>&5
+  ac_status=$?
+  $as_echo "$as_me:${as_lineno-$LINENO}: \$? = $ac_status" >&5
+  test $ac_status = 0; }; then
+  pkg_cv_GLIB2_18_CFLAGS=`$PKG_CONFIG --cflags "glib-2.0 >= 2.18.0" 2>/dev/null`
+else
+  pkg_failed=yes
+fi
+ else
+    pkg_failed=untried
+fi
+if test -n "$GLIB2_18_LIBS"; then
+    pkg_cv_GLIB2_18_LIBS="$GLIB2_18_LIBS"
+ elif test -n "$PKG_CONFIG"; then
+    if test -n "$PKG_CONFIG" && \
+    { { $as_echo "$as_me:${as_lineno-$LINENO}: \$PKG_CONFIG --exists --print-errors \"glib-2.0 >= 2.18.0\""; } >&5
+  ($PKG_CONFIG --exists --print-errors "glib-2.0 >= 2.18.0") 2>&5
+  ac_status=$?
+  $as_echo "$as_me:${as_lineno-$LINENO}: \$? = $ac_status" >&5
+  test $ac_status = 0; }; then
+  pkg_cv_GLIB2_18_LIBS=`$PKG_CONFIG --libs "glib-2.0 >= 2.18.0" 2>/dev/null`
+else
+  pkg_failed=yes
+fi
+ else
+    pkg_failed=untried
+fi
+
+
+
+if test $pkg_failed = yes; then
+   	{ $as_echo "$as_me:${as_lineno-$LINENO}: result: no" >&5
+$as_echo "no" >&6; }
+
+if $PKG_CONFIG --atleast-pkgconfig-version 0.20; then
+        _pkg_short_errors_supported=yes
+else
+        _pkg_short_errors_supported=no
+fi
+        if test $_pkg_short_errors_supported = yes; then
+	        GLIB2_18_PKG_ERRORS=`$PKG_CONFIG --short-errors --print-errors "glib-2.0 >= 2.18.0" 2>&1`
+        else
+	        GLIB2_18_PKG_ERRORS=`$PKG_CONFIG --print-errors "glib-2.0 >= 2.18.0" 2>&1`
+        fi
+	# Put the nasty error message in config.log where it belongs
+	echo "$GLIB2_18_PKG_ERRORS" >&5
+
+	{ $as_echo "$as_me:${as_lineno-$LINENO}: Using GLIB 2.18 features" >&5
+$as_echo "$as_me: Using GLIB 2.18 features" >&6;}
+elif test $pkg_failed = untried; then
+     	{ $as_echo "$as_me:${as_lineno-$LINENO}: result: no" >&5
+$as_echo "no" >&6; }
+	{ $as_echo "$as_me:${as_lineno-$LINENO}: Using GLIB 2.18 features" >&5
+$as_echo "$as_me: Using GLIB 2.18 features" >&6;}
+else
+	GLIB2_18_CFLAGS=$pkg_cv_GLIB2_18_CFLAGS
+	GLIB2_18_LIBS=$pkg_cv_GLIB2_18_LIBS
+        { $as_echo "$as_me:${as_lineno-$LINENO}: result: yes" >&5
+$as_echo "yes" >&6; }
+	GLIB2_18_DEFINES="-DGLIB2_18_ENABLED"
+$as_echo "#define GLIB2_18_ENABLED 1" >>confdefs.h
+
+fi
 
 
 
